### ISSUE TITLE
Unable to run docsite check 

### ISSUE THREAD

**Issue by ryan-blunden** [sourcegraph/docs.sourcegraph.com#5]
![screenflow](https://user-images.githubusercontent.com/133014/52378170-dbb3fb80-2a1b-11e9-8c1d-ccf8d23201ae.gif)

```sh
[✱] ~/Projects/docs.sourcegraph.com
-> docsite check
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xc0 pc=0x12bcdb6]

goroutine 1 [running]:
net/http.(*ServeMux).ServeHTTP(0xc00099ea20, 0x183d500, 0xc000cd2e00, 0x0)
	/usr/local/Cellar/go/1.11.4/libexec/src/net/http/server.go:2353 +0x26
github.com/sourcegraph/docsite.(*Site).checkContentPage.func2(0xc0000cf500, 0x71)
	/Users/rb/Projects/docsite/check.go:85 +0x15f
github.com/sourcegraph/docsite.walkHTMLDocument(0xc0006af3b0, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:105 +0x113
github.com/sourcegraph/docsite.walkHTMLDocument(0xc0006af180, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc0006c8fc0, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc0006c8310, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc000354540, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc000354460, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc000353570, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc000352ee0, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.walkHTMLDocument(0xc000352e70, 0xc000dfdc38)
	/Users/rb/Projects/docsite/check.go:115 +0x5e
github.com/sourcegraph/docsite.(*Site).checkContentPage(0xc000165130, 0xc00070bf40, 0xc000cd2dc0, 0x4, 0x4, 0xc00069c100, 0x35)
	/Users/rb/Projects/docsite/check.go:91 +0x262
github.com/sourcegraph/docsite.(*Site).Check(0xc000165130, 0x183dec0, 0xc0000220c0, 0x0, 0x0, 0x0, 0x1c86920, 0x0, 0x1e496c0, 0x0)
	/Users/rb/Projects/docsite/check.go:26 +0x1a0
main.init.0.func1(0xc00000c070, 0x0, 0x0, 0x0, 0x0)
	/Users/rb/Projects/docsite/cmd/docsite/check.go:21 +0xb7
main.commander.run(0xc0003a2180, 0x2, 0x2, 0xc00008cd80, 0x1698517, 0x7, 0xc00002c940, 0xc00000c070, 0x1, 0x1)
	/Users/rb/Projects/docsite/cmd/docsite/cmd.go:117 +0x308
main.main()
	/Users/rb/Projects/docsite/cmd/docsite/main.go:46 +0xd5
```

**Comment by sqs** [comment]
Does it work if you run it from the sourcegraph repo? (It should work from both but just curious.)

**Comment by ryan-blunden** [comment]
Running at the root of the sourcegraph repo produces the same error.

Running it inside the `doc` directory doesn't error but I don't think it's checking anything.

**Comment by ryan-blunden** [comment]
Fixed by https://github.com/sourcegraph/sourcegraph/pull/2482
